### ISSUE TITLE
1 hour for deploying StackStorm is too slow

### ISSUE THREAD

**Issue by arm4b** [bitovi/github-actions-deploy-stackstorm#41]
Looks like the Action to deploy StackStorm is running for more than `1 hour` (https://github.com/bitovi/operations-stackstorm/actions/runs/4049048877).

It normally takes `10-15mins` to install StackStorm in the `ansible-st2` tests running `GH Actions -> Ansible -> Docker locally`. See https://github.com/StackStorm/ansible-st2/actions/runs/4049822952

We have to figure out where's the bottleneck and fix it because this is unacceptably slow, but quick look it's Ansible provisioning that takes the biggest chunk of time.

**Comment by PhillypHenning** [comment]
Going to  spend a few minutes messing around with https://techadminblog.com/get-execution-time-of-each-task-ansible/ to see if I can get the length of the tasks out of Ansible

**Comment by PhillypHenning** [comment]
Alright, I just started a [run](https://github.com/bitovi/operations-stackstorm/actions/runs/4058072668/jobs/6984578888) that has timers on. Here is an example log from it; 

``` TASK [Gathering Facts] *********************************************************
Tuesday 31 January 2023  20:32:30 +0000 (0:00:00.144)       0:00:00.144 ******* 
ok: [34.201.21.120]
TASK [install : Install required system packages] ******************************
Tuesday 31 January 2023  20:32:53 +0000 (0:00:22.382)       0:00:22.527 ******* ```

I expect we should be able to gleam some insight into which tasks are the bottlenecks at the very least
