### ISSUE TITLE
All AWS resources should have "tags.Name"

### ISSUE THREAD

**Issue by arm4b** [bitovi/github-actions-deploy-stackstorm#42]
Many of the created AWS resources managed by Terraform in this repo have tags.Name, but some are missing due to oversight:

![image](https://user-images.githubusercontent.com/1533818/215860853-f22251bc-ac00-4c52-9d01-34114093db93.png)
![image](https://user-images.githubusercontent.com/1533818/215862323-421e8e35-12c4-4480-a775-2c5c3d2931ac.png)
https://github.com/bitovi/github-actions-deploy-stackstorm/blob/6d3705db9259b098dca7e665bf9bcbd268fd6a60/operations/deployment/terraform/modules/02_networking.tf#L65-L82

Identify all the resources without Name tag and make sure that's in place as `tags.Name` is the first identifier users see in the AWS UI.

**Comment by PhillypHenning** [comment]
Agreed that this is very much needed

**Comment by mickmcgrath13** [comment]
I suppose it wouldn't work to add it to the default tags? https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/main/operations/_scripts/generate/generate_provider.sh#L35
