### ISSUE TITLE
More specific naming for security groups

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/github-actions-deploy-stackstorm#8]
in `operations/deployment/terraform/modules/02_networking.tf`, the name property for `aws_security_group.allow_https` is too generic to be re-used in some existing VPC that might lead to conflicts.

Something like `st2_allow_https` might work better.  The same should be done for all security group configuration (http, ssh).

**Comment by mickmcgrath13** [comment]
Possibly resolved via: https://github.com/bitovi/github-actions-deploy-stackstorm/pull/25

@armab thoughts?

**Comment by armab** [comment]
That should work!
